name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  actions: write

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        for i in {1..3}; do
          sudo apt-get update && \
          sudo apt-get install -y xvfb libxkbcommon-x11-0 libxcb-icccm4 \
            libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 \
            libxcb-xinerama0 libxcb-xfixes0 x11-utils libxcb-cursor0 \
            libegl1 libopengl0 libgl1-mesa-dev && break || sleep 15
        done

    - name: Install Python dependencies
      run: |
        for i in {1..3}; do
          python -m pip install --upgrade pip && \
          pip install -r requirements.txt && break || sleep 15
        done

    - name: Run tests with coverage
      env:
        QT_QPA_PLATFORM: offscreen
        DISPLAY: ":99.0"
        XDG_RUNTIME_DIR: "/tmp/runtime-runner"
        PYTHONPATH: "."
      run: |
        mkdir -p /tmp/runtime-runner
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        sleep 3
        pytest tests/ --cov=. --cov-report=xml -v

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        files: ./coverage.xml
        flags: unittests
        name: invoice-generator
        fail_ci_if_error: false
        verbose: true
        directory: .
        token: ${{ secrets.CODECOV_TOKEN }}

  build-macos:
    needs: test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [macos-latest-xlarge, macos-14]
        include:
          - os: macos-latest-xlarge
            arch: intel
          - os: macos-14
            arch: arm64
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install gettext on macOS
      run: |
        for i in {1..3}; do
          brew install gettext && \
          brew link gettext --force && break || sleep 15
        done

    - name: Install Python dependencies
      run: |
        for i in {1..3}; do
          python -m pip install --upgrade pip setuptools wheel && \
          pip install -r requirements.txt && \
          pip install pyinstaller && break || sleep 15
        done

    - name: Build application
      env:
        DYLD_LIBRARY_PATH: /usr/local/opt/gettext/lib:$DYLD_LIBRARY_PATH
      run: |
        pyinstaller --clean --windowed --name "InvoiceGenerator-${{ matrix.arch }}" invoice_app.py

    - name: Import Code-Signing Certificates
      env:
        CERTIFICATE_BASE64: ${{ secrets.MACOS_CERTIFICATE }}
        CERTIFICATE_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      run: |
        # Create keychain
        security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
        
        # Import certificate
        echo "$CERTIFICATE_BASE64" | base64 --decode > certificate.p12
        security import certificate.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain
        
        # Clean up
        rm certificate.p12

    - name: Sign Application
      env:
        APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      run: |
        # Sign the app bundle
        codesign --force --options runtime --sign "Developer ID Application: $APPLE_TEAM_ID" \
          --timestamp --verbose "dist/InvoiceGenerator-${{ matrix.arch }}/InvoiceGenerator-${{ matrix.arch }}.app"
        
        # Verify signature
        codesign --verify --verbose "dist/InvoiceGenerator-${{ matrix.arch }}/InvoiceGenerator-${{ matrix.arch }}.app"

    - name: Create DMG
      run: |
        # Create a temporary DMG
        hdiutil create -srcfolder "dist/InvoiceGenerator-${{ matrix.arch }}" \
          -volname "InvoiceGenerator-${{ matrix.arch }}" \
          -fs HFS+ \
          -fsargs "-c c=64,a=16,e=16" \
          -format UDRW \
          "dist/InvoiceGenerator-${{ matrix.arch }}.dmg"

    - name: Sign DMG
      env:
        APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      run: |
        # Sign the DMG
        codesign --force --sign "Developer ID Application: $APPLE_TEAM_ID" \
          --timestamp --verbose "dist/InvoiceGenerator-${{ matrix.arch }}.dmg"

    - name: Notarize
      env:
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_APP_PASSWORD: ${{ secrets.APPLE_APP_PASSWORD }}
        APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      run: |
        # Submit for notarization
        xcrun notarytool submit "dist/InvoiceGenerator-${{ matrix.arch }}.dmg" \
          --apple-id "$APPLE_ID" \
          --password "$APPLE_APP_PASSWORD" \
          --team-id "$APPLE_TEAM_ID" \
          --wait
        
        # Staple the notarization ticket
        xcrun stapler staple "dist/InvoiceGenerator-${{ matrix.arch }}.dmg"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: InvoiceGenerator-${{ matrix.arch }}
        path: dist/InvoiceGenerator-${{ matrix.arch }}.dmg
        retention-days: 5
        
  create-release:
    needs: build-macos
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    timeout-minutes: 10
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        files: |
          InvoiceGenerator-intel/*.dmg
          InvoiceGenerator-arm64/*.dmg
        prerelease: ${{ github.ref == 'refs/heads/develop' }}
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: false
        generate_release_notes: true
